### ISSUE TITLE
Test-Cases überlegen

### ISSUE THREAD

**Issue by MaxPtg** [ABV-Tool/ABV_Tool#15]
Erste Überlegungen zu Test-Cases machen und abwägen, GitHub Actions zu nutzen

**Comment by MaxPtg** [comment]
Ich weiß nicht genau, wie die Test-Cases (**TC**) aufgebaut sein müssen, weshalb ich mich erstmal an der Dokumentation des alten ABV-Tools orientiert habe.
Außerdem ist mir unklar, ob ich die Tests nicht noch in kleinere Tests aufteilen sollte. 
(z.B. _Falsche Logindaten => TC01 - Falsches PW + TC02 Falscher Benutzername_)
Das Gleiche wäre dann auch bei den Anträgen und den Tagesordnungen der Fall.

**Comment by mirjammueller** [comment]
Finde die Test Cases (und den Aufbau) gut, ich würde es nicht mehr kleinteiliger machen.
