### ISSUE TITLE
UC 1 umsetzen 

### ISSUE THREAD

**Issue by mirjammueller** [ABV-Tool/ABV_Tool#28]

**Comment by MaxPtg** [comment]
So, folgendes ist schon geschafft:

Ich habe erstmal das gesamte CSS neu organisiert und erstmal alles entfernt, was mir unnütz erschien. Danach habe ich TailwindCSS installiert und damit (von der Navbar abgesehen) die gesamte Seite neu gebaut.

Anscheinend lässt sich Tailwind nur via `npm` builden (obwohl ich es via `pip` installiert habe) und muss für den Compiler über die `manage.py` parallel gestartet werden (`python .\manage.py tailwind start`). 
Wenn später alles fertig ist, kann man alles in eine CSS-Datei packen, womit man den Prozess nicht mehr starten muss (außer man ändert etwas am Design => `python .\manage.py tailwind build`)

Ansonsten wäre noch die Idee, die Texte auf der Homepage zu kürzen und mittels eines Info-Buttons den Langtext als Popup anzuzeigen (die Texte sind viel zu lang, das ließt sich so doch keiner Durch).

**Comment by MaxPtg** [comment]
## TLDR
Form-Handling mit Datenbank-Speicherung funzt, Front-End noch nicht angefangen, Einige Fehler sind noch zu besprechen und Fragen zu klären

---

Nochmal ein "kleines" Update:

### Form Handling & DB-Speicherung
Ich habe das DB-Model nochmal ein wenig angepasst und die gesamten, antragsspezifischen Inhalte mit zum Antrag gepackt (Kostenposition, Grund, weiteres Vorgehen, etc.). Weiterhin funktioniert das Form-Handling und alle Anträge werden in die Datenbank gespeichert und jeweils der nächsten Sitzung (ab nächstem Tag) zugeordnet.

### Initiale Daten
Damit wir alle einheitliche Daten zum Testen haben, habe ich sog. `fixtures` eingerichtet, womit initiale Daten in die DB eingetragen werden. Das ist primär für statische Sachen wie Referate, Antragstyp und noch testweise für Sitzungen. 

### Admin & Frontend
Die Admin-Sicht habe ich auch ein wenig angepasst, damit hier auch brauchbare Daten angezeigt werden. Das Front-End hingegen ist erstmal liegen geblieben, da ich erstmal das Backend zum Laufen bringen wollte.

### Fehler & Fragen
Ich habe einige Fehler sowie fehlende Features herausschreiben können, über die wir nochmal reden müssen, inwiefern diese relevant sind:
- Fehler sollte es keine Sitzungen zu dem Referat geben
- Fehler, sollte die DB-Verbindung abbrechen
	- Sowohl wenn sie initial nicht verfügbar ist als auch bei Antragsabsendung
- Antrag Veranstaltung: Soll für Zeitraum Date-Range eingefügt werden oder reicht Text?
- Keine überprüfung sollte ein Antrag mehrfach eingereicht werden
	- Generell: Anträge können gespammt werden => Kontermaßnahmen überlegen
- Fehler bei der Datenmigrierung: Abfrage der Referate in `forms.py` kann dafür sorgen, dass nichts mehr geht????
	
Die Fragen & Features sind folgende:
- File-Upload korrekt einrichten
- Überarbeitung: Speicherung der Antragsspezifischen Daten in Antrag oder anderswo? Überarbeitung DB-Schema?
- DB-Überarbeitung:
	- Antrag: Einreichdatum, Änderungsdatum, Status hinzufügen
	- Antragstyp: Noch Sinnvoll oder direkt bei Antrag abspeichern?
	- Referat: Neben Zyklus noch Initiale Sitzung o. ä.?
	- Andere Ideen?
- Antrag: Anzeige der nächsten Sitzung sobald das Referat ausgewählt wurde
- Überlegungen zu Feedback: Popups/Modals/Toasts einbinden? Reicht farblicher Text der hervorsticht?
